version: 2
jobs:
  build:
    working_directory: ~/circle-bug
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo $AWS_DEFAULT_REGION

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build:
          context: org-global
